github-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpgIBAAKCAQEA1oi74zlTyyZxgykb8NOqHcWQq6v6cphD413XfKSgkURcQAnv
  sbWetJaSH4G14Ot4h20xgt5draY2uKSiL3q7SDNH6lmvUGTZS1Tk8ShYSHsnOZqr
  pt1oeYXZiFuVnsyH7hMuQ9Yyzgerh5Fa0YQHcOMiuITHxCma3uPf/NZPfV/M1aJ+
  gIyvRfKlK8qh2RcdoDHTwwMShNVcGbjD6R01PBRhq4rJdBO+LykCcoYJ6NaSdyr/
  +UmTFYmhI3Urmx+PJEOUzgD4Dcqn/BS3ddUs4bAuU4KJjIcUpfL+oERc8cqB7le0
  INfVY/IGappxs7CeljmKS/YP1qKkkPg2DXX18wIDAQABAoIBAQCubWv+Wm0DvpUK
  ZFFAZIhrPmfa/LBbneuMoI8E28FleyRaOPn3DkkkYUwba9YaMrnDuodH9U5LUtop
  FEp9uhcto+wz4YmGHwkBk9u1K+1juSXyUwx/VoOMUsTEdlpXS8q1SkkShMS3+UqA
  pjEmKmf2Y+amCed2WbF+yd4i74if0NhYIblc43BH7Oi57WFsDpq2YZasJAUHjLQp
  /hzfJIeBqbLLVILVcDvd7ISFElDHm4CCYtZU4ekZg7kDOm7g9IxXjd5AqMHAwogl
  A9RcGQgwkK5en/wLn2cdsLyWp0GY8LLn40BLUXLmQG69JUmAnZKVzPLl51lSx6Nk
  TjPfKRQ5AoGBAO00fLQ1tgs3hmkEwAWecBzKclvghkzCVTpLA9KzsTy8tSWSxI5Z
  jC0vHHyhW7XxM/XtNdzFRuVugBk3067l1O5EIGXkLk+OgSwtTUoyWaFsQ7iJX4Yu
  HBZvhwyptHnWjPIvV2XMNz/vnTpwhe+E0IQoiJtHKNr7AzSM2SFdSvFXAoGBAOeI
  YrnrxBrWYkb3x88REg9ORLxrjWKYXOEL1M4rVx3epDB/ubIODCpElz3TZnDXhEks
  ne4j8saoOE7zXRn41rPmeS6fYR6l8Qa8xvf1+hSYmg3Ca1WtzFIk6lFLRymUncKE
  BHOF7Q28131bC9fZmkGu3UxrwL4uHR5fBZBkyvLFAoGBALWCdW5cr1mz+llANkPW
  cknFrG6bx4jTJ+58WoeP0y77483FmjynTzmAFFdWDdySnsUv6AhwuQh1XvZtHsF1
  w1MztGrjiYB9NmD8pWkCUE3Sj5uVGxCNFhcg7oGFFsIoqB/mlAUkmJ6HF5QRaJvY
  0MpgTfAsKpoue8xpfvkl72PvAoGBAKduwH5U2cbSm9VYX/0FCjtZTWm4mVDgf+Ia
  rTS+sMwf8jpEU2RItlFmsrx6AM2/fKFyC29oPaudgMLPSNd8VL9Z/u5RQWlpdSh7
  IaO1FLkKNfWXUAlwmp4Ypf5N4tNV7tP4pkNoaSoTEv5K9gCNEvlG3C/kiEi/jj0l
  WB+4U+9FAoGBAIHQWmZVilh9a6+2ZOHyz/XypspKW5ZSoe0si4gF/v1HgwQtqbXM
  mkt7E5X8dJo9g8xYD+EFRpIQ7AWxQ9EAgST5xKR1+IKl+xOnY40WoMfQtGsyKmYC
  bz92BElZTv8G8dWRn4m+OYC+8PVL3RoYVn9lrm4RyZr4lebFVY5Scfb6
  -----END RSA PRIVATE KEY-----

docker:
  user: kwexample
  password: yEg#tS#q9R5SVf#+8!

app:
  docker-image: kwexample/concourse-example-app
  git-repo: git@github.com:kw-concourse-example/concourse-example-app

ci:
  git-repo: git@github.com:kw-concourse-example/concourse-app-release-lifecycle-example