---
platform: linux
params:
  DOCKER_PATH: "./"
  CODE_ARTIFACT_SOURCE_FILENAME: ""
  CODE_ARTIFACT_DEST_FILENAME: "app.tgz"

image_resource:
  type: docker-image
  source:
    repository: debian
    tag: "stretch"

inputs:
- name: docker-repo
- name: code-artificat

outputs:
- name: docker-build-context

run:
  path: sh
  args:
  - -ec
  - |
    export CI_BASE=`pwd`
    export OUTPUT_FOLDER="$CI_BASE/docker-build-context"

    # make us relative to the code
    cd $CI_BASE/docker-repo

    # copy our whole docker context to our output folder
    cp -fr $DOCKER_PATH/* $OUTPUT_FOLDER/

    # add our code artifact to the docker context
    cp ${CI_BASE}/code-artificat/$CODE_ARTIFACT_SOURCE_FILENAME $OUTPUT_FOLDER/$CODE_ARTIFACT_DEST_FILENAME