---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: debian
    tag: "stretch"

inputs:
- name: code
- name: version

outputs:
- name: artifact


run:
  path: sh
  args:
  - -ec
  - |
    export CI_BASE=`pwd`
    export OUTPUT_FOLDER="$CI_BASE/artifact"
    export VERSION=`cat $CI_BASE/version/version`
    export COMMITREF=`cat $CI_BASE/code/.git/ref`
    # make us relative to the code
    cd $CI_BASE/code

    # debug info
    echo "git commit ref is: $COMMITREF"
    echo "version is: $VERSION"

    # create / simulate something "we compile" so that is our compile step and our compiled source lands in ./target
    mkdir -p ./target
    echo $COMMITREF ./target/.commitref
    echo $VERSION > ./target/.version
    echo "code" > ./target/code

    # package our code and put it into our putput folder
    echo "creating output artifact to $OUTPUT_FOLDER/myapp-$VERSION.tgz"
    tar czf $OUTPUT_FOLDER/myapp-$VERSION.tgz target
