---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: debian
    tag: "stretch"

inputs:
- name: code-artifact
- name: promote-to-version
- name: drupal_version

outputs:
- name: transformed-artifact

run:
  path: sh
  args:
  - -ec
  - |
    export CI_BASE=`pwd`
    export OUTPUT_FOLDER="$CI_BASE/transformed-artifact"
    export PROMOTE_TO_VERSION=`cat $CI_BASE/promote-to-version/version`

    mkdir -p package_dir && cd package_dir
    tar xzf ${CI_BASE}/code-artifact/myapp*.tgz -C ./

    export PREVIOUS_VERSION=$(cat target/.version)
    export COMMITREF=$(cat target/.commitref)
    echo "TRANSFORMING ARTIFACT WITH COMMITREF: ${COMMITREF}"
    echo "TRANSFORMING ARTIFACT FROM VERSION: ${PREVIOUS_VERSION}"
    echo "TRANSFORMING ARTIFACT TO VERSION: ${PROMOTE_TO_VERSION}"

    echo ${PROMOTE_TO_VERSION} > target/.version

    tar czf myapp-$PROMOTE_TO_VERSION.tgz target

    mv myapp-$PROMOTE_TO_VERSION.tgz ${CI_BASE}/transformed-artifact/