---
platform: linux
params:
  GIT_PRIVATE_KEY: ""
  ORIGIN_BRANCH: "develop"
  TARGET_BRANCH: "master"

image_resource:
  type: docker-image
  source:
    repository: eugenmayer/golang-builder

inputs:
  - name: repo
  - name: artifact

outputs:
  - name: repo-modified

run:
  path: sh
  args:
  - -ec
  - |

    # ---------------------------------------- git ssh key / config deployment
    echo  "Deploy git ssh key"
    mkdir -p ~/.ssh
    echo "${GIT_PRIVATE_KEY}" >> ~/.ssh/id_rsa

    echo our ssh config for our dwdev alias
    echo 'Host *' >> ~/.ssh/config
    echo '  UserKnownHostsFile=/dev/null' >> ~/.ssh/config
    echo '  StrictHostKeyChecking=no' >> ~/.ssh/config

    chmod u=r,g=,o=  ~/.ssh/*
    eval "$(ssh-agent -s)"; ssh-add ~/.ssh/id_rsa
    # ------------------------------------------------------------------------

    export CI_BASE=$(pwd)
    # Extract artifact and export infos into env
    cd ${CI_BASE}/artifact
    tar xzf myapp*.tgz
    export VERSION=$(cat target/version)
    export SHASUM=$(cat target/shasum)
    echo "VERSION: $VERSION"
    echo "SHASUM: $SHASUM"

    # Copy the repo by using the local inout directory
    cd ${CI_BASE}
    git clone ./repo ./repo-modified
    echo "Merging ${ORIGIN_BRANCH} ${SHASUM} into ${TARGET_BRANCH}."

    # Start git manipulations
    cd repo-modified

    # Pull both specified branches - be sure to have both available. This makes the thing easier for the caller.
    git pull origin ${ORIGIN_BRANCH}
    git pull origin ${TARGET_BRANCH}

    # Make sure we are on the specified origin branch, the param has higher precedence than the passed repo
    git checkout ${ORIGIN_BRANCH}

    # Reset hard to be sure we are on the shasum of the commit of the artifact passed into this task.
    git reset --hard ${SHASUM}

    # Merge
    git checkout ${TARGET_BRANCH}
    git merge ${ORIGIN_BRANCH}
    git tag -a ${VERSION} -m "Auto Tagging by Kontextwork Concourse CI" ${SHASUM}
    git commit -am "Merge ${ORIGIN_BRANCH} (${SHASUM}) into ${TARGET_BRANCH}."