groups:
- name: staging
  jobs:
  - staging-build-app-artifiact
  - staging-build-app-code-image
  - promote-to-candidate
  - promote-to-release
  - merge-master-and-tag-with-release-version

jobs: []
# jobs and job specific resourcs are all in pipeline/jobs/*

resources: []
# all common resources are under _common_resources.yaml - all those we use in several jobs

resource_types:
  - name: docker-image-resource-ng
    type: docker-image
    privileged: true
    source:
      repository: eugenmayer/concourse-docker-image-resource
      tag: latest

