groups:
- name: staging
  jobs:
  - staging-build-app-artifiact
  - staging-build-app-code-image
  - promote-to-candidate
  - promote-to-release
  - merge-master-and-tag-with-release-version

jobs: []
# jobs and job specific resourcs are all in pipeline/jobs/*

resources: []
# all global resources are under _global_resources.yaml - all those we use in several jobs

resource_types: []
# all the global resource types can be found under _resource_types.yaml

