resources:
- name: ci-repo
  type: git
  source:
    uri: git@github.com:kw-concourse-example/concourse-app-release-lifecycle-example
    private_key: ((github-private-key))
    branch: master

- name: app-repo
  type: git
  source:
    uri: git@github.com:kw-concourse-example/concourse-example-app
    private_key: ((github-private-key))
    branch: master

jobs:
- name: build-app
  plan:
  - get: ci-repo
  - get: app-repo
    trigger: true
  - task: build-artificat
    file: ci-repo/ci/tasks/build-artifact.yaml
    input_mapping:
      app: app-repo