jobs:
  #######################################################################
  ###################### app-code: artifact #############################
  #######################################################################

  # A start and fake tag/push is not needed anymore. The author (vito) stated, that all resources should be checked
  # when a task is run manually. This behavior was broken several months ago, and seems to be fixed now, while the issue
  # mentioning this bug was not fixed with a PR linked to the issue itself (which is common practice in concourse).
  #
  # Issue was: https://github.com/concourse/concourse/issues/1719#issuecomment-336722092
  - name: staging-build-code-artifact
    plan:
    - get: code-develop-repo
      trigger: true
    - get: app-ci-repo
    - get: staging-code-version
    - task: build-artificat
      file: app-ci-repo/ci/tasks/build-artifact.yaml
      input_mapping:
        app: code-develop-repo
        version: staging-code-version
      output_mapping:
        artifact: code-artifact
    # deploy / publish our artifact to our artifact storage
    - put: publish-staging-artificat
      resource: code-artifact
      params:
        # this is NOT regexp bu bashism wildcard!!
        file: code-artifact/myapp-*.tgz
    # be sure we save our bumped version
    - put: save-staging-version
      resource: staging-code-version
      params:
        file: staging-code-version/version

  #######################################################################
  ###################### app-code: Docker image #########################
  #######################################################################
  - name: staging-build-code-image
    plan:
    - get: code-artifact
      passed: [staging-build-code-artifact]
      trigger: true
    - get: staging-code-version
      passed: [staging-build-code-artifact]
    - get: app-ci-repo
    - get: code-develop-repo
    - task: staging-build-code-image
      file: app-ci-repo/ci/tasks/build-docker-context.yaml
      params:
        # the folder our Dockerfile and other docker context files are located in the input docker-repo
        DOCKER_PATH: './docker'
        # the filename of our app artifact in the code-artifact input
        APP_ARTIFACT_SOURCE_FILENAME: myapp-*.tgz
        # the expected filename of the app artifact in the Dockerfile of the app app-code image, see
        # https://github.com/kw-concourse-example/concourse-example-app/blob/master/docker/Dockerfile#L5
        APP_ARTIFACT_DEST_FILENAME: myapp.tgz
      input_mapping:
        # the input where are Dockerfile is located
        docker-repo: code-develop-repo
        # the input of our app artifact
        app-artificat: code-artifact
      output_mapping:
        # this will be a prepared docker-context, so the Dockerfile including all folders and the app artifact to build
        # using the docker-resource
        docker-build-context: build-context
    - put: app-code-docker-image
      get_params:
        skip_download : true
      params:
        build: build-context
        tag_as_latest: true
        # tag_file: staging-code-version/version

resources:
  - name: staging-code-version
    type: semver
    source:
      driver: git
      uri: ((app.git-repo))
      branch: version
      file: staging-version
      private_key: ((github-private-key))